export const defaultPaymentForms = [
  {
    id: "FORM-DEP-001",
    name: "Main Deposit Checkout",
    slug: "main-deposit",
    environment: "Production",
    methods: ["Visa", "Mastercard", "D17", "Flouci"],
    status: "Published",
    sessions: 18420,
    conversion: "68.4%",
    updated: "18 Sep 2026, 09:22",
  },
  {
    id: "FORM-DEP-002",
    name: "VIP Deposit",
    slug: "vip-deposit",
    environment: "Production",
    methods: ["Visa", "Mastercard", "Kashy"],
    status: "Published",
    sessions: 6210,
    conversion: "74.1%",
    updated: "17 Sep 2026, 16:05",
  },
  {
    id: "FORM-DEP-003",
    name: "Mobile Wallet Checkout",
    slug: "wallet-mobile",
    environment: "Sandbox",
    methods: ["D17", "Flouci", "e-Dinar"],
    status: "Draft",
    sessions: 842,
    conversion: "61.8%",
    updated: "16 Sep 2026, 11:44",
  },
] as const;
