import type { UserRole } from "@/stores/auth/auth-provider";

export const roleNavigation: Record<UserRole, Record<string, boolean>> = {
  "SaaS Owner": {
    dashboard: true,
    players: true,
    distributors: true,
    deposits: true,
    withdrawls: true,
    analytics: true,
    disagreements: true,
    transactions: true,
    settlements: true,
    reconciliation: true,
    "fees-revenue": true,
    settings: true,
    portal: true,
  },
  "Brand Admin": {
    dashboard: true,
    players: true,
    distributors: true,
    deposits: true,
    withdrawls: true,
    analytics: true,
    disagreements: true,
    transactions: true,
    settlements: true,
    reconciliation: true,
    "fees-revenue": true,
    settings: true,
    portal: true,
  },
  Supervisor: {
    dashboard: true,
    players: true,
    distributors: true,
    deposits: true,
    withdrawls: true,
    analytics: true,
    disagreements: true,
    transactions: true,
    settlements: true,
    reconciliation: false,
    "fees-revenue": false,
    settings: false,
    portal: false,
  },
  Agent: {
    dashboard: true,
    players: true,
    distributors: false,
    deposits: true,
    withdrawls: true,
    analytics: false,
    disagreements: true,
    transactions: true,
    settlements: false,
    reconciliation: false,
    "fees-revenue": false,
    settings: false,
    portal: false,
  },
  Assistant: {
    dashboard: true,
    players: true,
    distributors: true,
    deposits: true,
    withdrawls: false,
    analytics: false,
    disagreements: false,
    transactions: true,
    settlements: false,
    reconciliation: false,
    "fees-revenue": false,
    settings: false,
    portal: false,
  },
};
