import { createFileRoute } from "@tanstack/react-router";
import { ArrowDownToLine, ArrowUpFromLine, CircleDollarSign, Percent } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type RevenueRow = {
  date: string;
  provider: string;
  deposits: number;
  withdrawals: number;
  grossFees: number;
  providerCost: number;
  revenue: number;
};

const rows: RevenueRow[] = [
  { date: "28 Sep 2026", provider: "Flouci", deposits: 18420, withdrawals: 4120, grossFees: 316.2, providerCost: 121.4, revenue: 194.8 },
  { date: "28 Sep 2026", provider: "D17", deposits: 12780, withdrawals: 2980, grossFees: 263.5, providerCost: 102.3, revenue: 161.2 },
  { date: "27 Sep 2026", provider: "Tunisie Telecom", deposits: 9630, withdrawals: 1820, grossFees: 149.7, providerCost: 57.5, revenue: 92.2 },
  { date: "27 Sep 2026", provider: "Kashy", deposits: 7410, withdrawals: 2260, grossFees: 184.3, providerCost: 71.1, revenue: 113.2 },
  { date: "26 Sep 2026", provider: "Orange", deposits: 11340, withdrawals: 3260, grossFees: 275.9, providerCost: 105.8, revenue: 170.1 },
  { date: "26 Sep 2026", provider: "Ooredoo", deposits: 5210, withdrawals: 1190, grossFees: 112.4, providerCost: 44.8, revenue: 67.6 },
];

const money = (value: number) => "$" + value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function Metric({ label, value, sub, icon }: { label: string; value: string; sub: string; icon: React.ReactNode }) {
  return <Card><CardContent className="flex min-h-[112px] items-center justify-between gap-4 p-4"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">{sub}</p></div><div className="flex size-10 shrink-0 items-center justify-center rounded-xl border bg-primary/10 text-primary">{icon}</div></CardContent></Card>;
}

export const Route = createFileRoute("/(main)/dashboard/transactions/fees-revenue")({
  component: FeesRevenuePage,
});

function FeesRevenuePage() {
  const feeTotal = rows.reduce((sum, row) => sum + row.grossFees, 0);
  const costTotal = rows.reduce((sum, row) => sum + row.providerCost, 0);
  const revenueTotal = rows.reduce((sum, row) => sum + row.revenue, 0);
  const volume = rows.reduce((sum, row) => sum + row.deposits + row.withdrawals, 0);
  const takeRate = volume ? (feeTotal / volume) * 100 : 0;

  return (
    <section className="flex min-h-full flex-col gap-5 bg-background">
      <header className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5">
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div className="flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl border bg-primary/10 text-primary"><CircleDollarSign className="size-5" /></div><div><div className="text-xs font-medium text-muted-foreground">Finance</div><h1 className="mt-0.5 text-2xl font-semibold tracking-tight">Fees &amp; Revenue</h1><p className="mt-1 text-sm text-muted-foreground">Monitor transaction fees, provider costs and the net platform revenue generated by payment activity.</p></div></div>
          <div className="flex gap-2"><Button variant="outline" size="sm">Sep 23 — Sep 28, 2026</Button><Button size="sm">Export CSV</Button></div>
        </div>
      </header>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric label="Processed volume" value={money(volume)} sub="Deposits + withdrawals" icon={<ArrowDownToLine className="size-5" />} />
        <Metric label="Gross fees" value={money(feeTotal)} sub={takeRate.toFixed(2) + "% blended fee rate"} icon={<Percent className="size-5" />} />
        <Metric label="Provider cost" value={money(costTotal)} sub="Estimated channel cost" icon={<ArrowUpFromLine className="size-5" />} />
        <Metric label="Net revenue" value={money(revenueTotal)} sub="Fees less provider cost" icon={<CircleDollarSign className="size-5" />} />
      </div>

      <Card className="overflow-hidden">
        <div className="flex flex-col gap-3 border-b p-3 md:flex-row md:items-center"><Input placeholder="Search provider..." className="md:max-w-[360px]" /><Badge variant="secondary" className="w-fit">Mock finance data</Badge></div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="border-b bg-muted/30 text-xs text-muted-foreground"><tr>{["Date", "Provider", "Deposits", "Withdrawals", "Gross fees", "Provider cost", "Net revenue"].map((head) => <th key={head} className="px-4 py-3 text-left font-medium whitespace-nowrap">{head}</th>)}</tr></thead>
            <tbody className="divide-y">
              {rows.map((row) => <tr key={row.date + row.provider} className="hover:bg-muted/20">
                <td className="px-4 py-3 whitespace-nowrap">{row.date}</td><td className="px-4 py-3 font-medium">{row.provider}</td><td className="px-4 py-3 tabular-nums">{money(row.deposits)}</td><td className="px-4 py-3 tabular-nums">{money(row.withdrawals)}</td><td className="px-4 py-3 tabular-nums">{money(row.grossFees)}</td><td className="px-4 py-3 tabular-nums text-muted-foreground">{money(row.providerCost)}</td><td className="px-4 py-3 font-semibold tabular-nums">{money(row.revenue)}</td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </Card>
    </section>
  );
}
