/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as externalIndexRouteImport } from './routes/(external)/index'
import { Route as mainChatRouteRouteImport } from './routes/(main)/chat/route'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainMailRouteRouteImport } from './routes/(main)/mail/route'
import { Route as mainUnauthorizedRouteImport } from './routes/(main)/unauthorized'
import { Route as mainAuthV2RouteRouteImport } from './routes/(main)/auth/v2/route'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardSplatRouteImport } from './routes/(main)/dashboard/$'
import { Route as mainDashboardAnalyticsRouteRouteImport } from './routes/(main)/dashboard/analytics/route'
import { Route as mainDashboardSettingsRouteRouteImport } from './routes/(main)/dashboard/settings/route'
import { Route as mainDashboardSettingsGeneralRouteRouteImport } from './routes/(main)/dashboard/settings/general/route'
import { Route as mainDashboardSettingsLanguagesRouteRouteImport } from './routes/(main)/dashboard/settings/languages/route'
import { Route as mainDashboardSettingsSecurityRouteRouteImport } from './routes/(main)/dashboard/settings/security/route'
import { Route as mainDashboardSettingsNotificationsRouteRouteImport } from './routes/(main)/dashboard/settings/notifications/route'
import { Route as mainDashboardSettingsAuditLogRouteRouteImport } from './routes/(main)/dashboard/settings/audit-log/route'
import { Route as mainDashboardSettingsBillingRouteRouteImport } from './routes/(main)/dashboard/settings/billing/route'
import { Route as mainDashboardSettingsFeaturesRouteRouteImport } from './routes/(main)/dashboard/settings/features/route'
import { Route as mainDashboardSettingsCustomDomainRouteRouteImport } from './routes/(main)/dashboard/settings/custom-domain/route'
import { Route as mainDashboardSettingsTeamAccessRouteRouteImport } from './routes/(main)/dashboard/settings/team-access/route'

import { Route as mainDashboardIntegrationsRouteRouteImport } from './routes/(main)/dashboard/integrations/route'
import { Route as mainDashboardPortalRouteRouteImport } from './routes/(main)/dashboard/portal/route'
import { Route as mainDashboardDepositsRouteRouteImport } from './routes/(main)/dashboard/deposits/route'
import { Route as mainDashboardDepositsDepoistDetailsRouteRouteImport } from './routes/(main)/dashboard/deposits/depoist-details/route'
import { Route as mainDashboardDepositsDepoistDetailsIndexRouteImport } from './routes/(main)/dashboard/deposits/depoist-details/index'
import { Route as mainDashboardDepositsDepoistDetailsVoucherRouteImport } from './routes/(main)/dashboard/deposits/depoist-details/voucher/route'
import { Route as mainDashboardDepositsIndexRouteImport } from './routes/(main)/dashboard/deposits/index'
import { Route as mainDashboardWithdrawlsRouteRouteImport } from './routes/(main)/dashboard/withdrawls/route'
import { Route as mainDashboardWithdrawlsAnalyticsRouteRouteImport } from './routes/(main)/dashboard/withdrawls_.analytics'
import { Route as mainDashboardPlayersRouteRouteImport } from './routes/(main)/dashboard/players/route'
import { Route as mainDashboardPlayersProfileRouteRouteImport } from './routes/(main)/dashboard/players/$playerId/route'
import { Route as mainDashboardDistributorsRouteRouteImport } from './routes/(main)/dashboard/distributors/route'
import { Route as mainDashboardDistributorsAccountRouteRouteImport } from './routes/(main)/dashboard/distributors_.account'
import { Route as mainDashboardAccountsRouteRouteImport } from './routes/(main)/dashboard/accounts/route'
import { Route as mainPortalRouteRouteImport } from './routes/(main)/portal/route'
import { Route as mainPortalMethodRouteRouteImport } from './routes/(main)/portal/$method/route'
import { Route as mainPortalTrackingDepoistRouteRouteImport } from './routes/(main)/portal/tracking-depoist/route'
import { Route as mainAuthV1LoginRouteRouteImport } from './routes/(main)/auth/v1/login/route'
import { Route as mainAuthV1RegisterRouteRouteImport } from './routes/(main)/auth/v1/register/route'
import { Route as mainAuthV2LoginRouteRouteImport } from './routes/(main)/auth/v2/login/route'
import { Route as mainAuthV2RegisterRouteRouteImport } from './routes/(main)/auth/v2/register/route'

const externalIndexRoute = externalIndexRouteImport.update({
  id: '/(external)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainChatRouteRoute = mainChatRouteRouteImport.update({
  id: '/(main)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/(main)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMailRouteRoute = mainMailRouteRouteImport.update({
  id: '/(main)/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const mainUnauthorizedRoute = mainUnauthorizedRouteImport.update({
  id: '/(main)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthV2RouteRoute = mainAuthV2RouteRouteImport.update({
  id: '/(main)/auth/v2',
  path: '/auth/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSplatRoute = mainDashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardAnalyticsRouteRoute =
  mainDashboardAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardSettingsRouteRoute = mainDashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSettingsGeneralRouteRoute = mainDashboardSettingsGeneralRouteRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsLanguagesRouteRoute = mainDashboardSettingsLanguagesRouteRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsSecurityRouteRoute = mainDashboardSettingsSecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsNotificationsRouteRoute = mainDashboardSettingsNotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsAuditLogRouteRoute = mainDashboardSettingsAuditLogRouteRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsBillingRouteRoute = mainDashboardSettingsBillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsFeaturesRouteRoute = mainDashboardSettingsFeaturesRouteRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsCustomDomainRouteRoute = mainDashboardSettingsCustomDomainRouteRouteImport.update({
  id: '/custom-domain',
  path: '/custom-domain',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)
const mainDashboardSettingsTeamAccessRouteRoute = mainDashboardSettingsTeamAccessRouteRouteImport.update({
  id: '/team-access',
  path: '/team-access',
  getParentRoute: () => mainDashboardSettingsRouteRoute,
} as any)

const mainDashboardIntegrationsRouteRoute = mainDashboardIntegrationsRouteRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardPortalRouteRoute = mainDashboardPortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)

const mainDashboardDepositsRouteRoute = mainDashboardDepositsRouteRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardDepositsIndexRoute = mainDashboardDepositsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardDepositsRouteRoute,
} as any)
const mainDashboardDepositsDepoistDetailsRouteRoute =
  mainDashboardDepositsDepoistDetailsRouteRouteImport.update({
    id: '/depoist-details',
    path: '/depoist-details',
    getParentRoute: () => mainDashboardDepositsRouteRoute,
  } as any)

const mainDashboardDepositsDepoistDetailsIndexRoute =
  mainDashboardDepositsDepoistDetailsIndexRouteImport.update({
    id: '/depoist-details/',
    path: '/',
    getParentRoute: () => mainDashboardDepositsDepoistDetailsRouteRoute,
  } as any)
const mainDashboardDepositsDepoistDetailsVoucherRouteRoute =
  mainDashboardDepositsDepoistDetailsVoucherRouteImport.update({
    id: '/voucher',
    path: '/voucher',
    getParentRoute: () => mainDashboardDepositsDepoistDetailsRouteRoute,
  } as any)
const mainDashboardWithdrawlsRouteRoute = mainDashboardWithdrawlsRouteRouteImport.update({
  id: '/withdrawls',
  path: '/withdrawls',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardWithdrawlsAnalyticsRouteRoute =
  mainDashboardWithdrawlsAnalyticsRouteRouteImport.update({
    id: '/withdrawls_/analytics',
    path: '/withdrawls/analytics',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardPlayersRouteRoute = mainDashboardPlayersRouteRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardPlayersProfileRouteRoute = mainDashboardPlayersProfileRouteRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => mainDashboardPlayersRouteRoute,
} as any)

const mainDashboardDistributorsRouteRoute = mainDashboardDistributorsRouteRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardDistributorsAccountRouteRoute =
  mainDashboardDistributorsAccountRouteRouteImport.update({
    id: '/distributors_/account',
    path: '/distributors/account',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardAccountsRouteRoute = mainDashboardAccountsRouteRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)

const mainPortalRouteRoute = mainPortalRouteRouteImport.update({
  id: '/(main)/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPortalMethodRouteRoute = mainPortalMethodRouteRouteImport.update({
  id: '/$method',
  path: '/$method',
  getParentRoute: () => mainPortalRouteRoute,
} as any)
const mainPortalTrackingDepoistRouteRoute = mainPortalTrackingDepoistRouteRouteImport.update({
  id: '/tracking-depoist',
  path: '/tracking-depoist',
  getParentRoute: () => mainPortalRouteRoute,
} as any)
const mainAuthV1LoginRouteRoute = mainAuthV1LoginRouteRouteImport.update({
  id: '/(main)/auth/v1/login',
  path: '/auth/v1/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthV1RegisterRouteRoute = mainAuthV1RegisterRouteRouteImport.update({
  id: '/(main)/auth/v1/register',
  path: '/auth/v1/register',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthV2LoginRouteRoute = mainAuthV2LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => mainAuthV2RouteRoute,
} as any)
const mainAuthV2RegisterRouteRoute = mainAuthV2RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => mainAuthV2RouteRoute,
} as any)
export interface FileRoutesByFullPath {
  '/chat': typeof mainChatRouteRoute
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/mail': typeof mainMailRouteRoute
  '/unauthorized': typeof mainUnauthorizedRoute
  '/': typeof externalIndexRoute
  '/auth/v2': typeof mainAuthV2RouteRouteWithChildren
  '/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/dashboard/settings': typeof mainDashboardSettingsRouteRouteWithChildren
  '/dashboard/settings/general': typeof mainDashboardSettingsGeneralRouteRoute
  '/dashboard/settings/languages': typeof mainDashboardSettingsLanguagesRouteRoute
  '/dashboard/settings/security': typeof mainDashboardSettingsSecurityRouteRoute
  '/dashboard/settings/notifications': typeof mainDashboardSettingsNotificationsRouteRoute
  '/dashboard/settings/audit-log': typeof mainDashboardSettingsAuditLogRouteRoute
  '/dashboard/settings/billing': typeof mainDashboardSettingsBillingRouteRoute
  '/dashboard/settings/features': typeof mainDashboardSettingsFeaturesRouteRoute
  '/dashboard/settings/custom-domain': typeof mainDashboardSettingsCustomDomainRouteRoute
  '/dashboard/settings/team-access': typeof mainDashboardSettingsTeamAccessRouteRoute
  '/dashboard/integrations': typeof mainDashboardIntegrationsRouteRoute
  '/dashboard/portal': typeof mainDashboardPortalRouteRoute
  '/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/dashboard/settings/general': typeof mainDashboardSettingsGeneralRouteRoute
  '/dashboard/settings/languages': typeof mainDashboardSettingsLanguagesRouteRoute
  '/dashboard/settings/security': typeof mainDashboardSettingsSecurityRouteRoute
  '/dashboard/settings/notifications': typeof mainDashboardSettingsNotificationsRouteRoute
  '/dashboard/settings/audit-log': typeof mainDashboardSettingsAuditLogRouteRoute
  '/dashboard/settings/billing': typeof mainDashboardSettingsBillingRouteRoute
  '/dashboard/settings/features': typeof mainDashboardSettingsFeaturesRouteRoute
  '/dashboard/integrations': typeof mainDashboardIntegrationsRouteRoute
  '/dashboard/portal': typeof mainDashboardPortalRouteRoute
  '/dashboard/deposits': typeof mainDashboardDepositsRouteRoute
  '/dashboard/deposits/': typeof mainDashboardDepositsIndexRoute
  '/dashboard/deposits/depoist-details': typeof mainDashboardDepositsDepoistDetailsRouteRoute
  '/dashboard/deposits/depoist-details/': typeof mainDashboardDepositsDepoistDetailsIndexRoute
  '/dashboard/deposits/depoist-details/voucher': typeof mainDashboardDepositsDepoistDetailsVoucherRouteRoute
  '/dashboard/withdrawls': typeof mainDashboardWithdrawlsRouteRoute
  '/dashboard/withdrawls/analytics': typeof mainDashboardWithdrawlsAnalyticsRouteRoute
  '/dashboard/players': typeof mainDashboardPlayersRouteRoute
  '/dashboard/players/$playerId': typeof mainDashboardPlayersProfileRouteRoute
  '/dashboard/distributors': typeof mainDashboardDistributorsRouteRoute
  '/dashboard/distributors/account': typeof mainDashboardDistributorsAccountRouteRoute
  '/dashboard/accounts': typeof mainDashboardAccountsRouteRoute
  '/portal': typeof mainPortalRouteRouteWithChildren
  '/portal/$method': typeof mainPortalMethodRouteRoute
  '/portal/tracking-depoist': typeof mainPortalTrackingDepoistRouteRoute
  '/dashboard/  '/dashboard/': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/auth/v1/register': typeof mainAuthV1RegisterRouteRoute
  '/auth/v2/login': typeof mainAuthV2LoginRouteRoute
  '/auth/v2/register': typeof mainAuthV2RegisterRouteRoute
}
: typeof mainDashboardSplatRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/auth/v1/register': typeof mainAuthV1RegisterRouteRoute
  '/auth/v2/login': typeof mainAuthV2LoginRouteRoute
  '/auth/v2/register': typeof mainAuthV2RegisterRouteRoute
}
export interface FileRoutesByTo {
  '/chat': typeof mainChatRouteRoute
  '/mail': typeof mainMailRouteRoute
  '/unauthorized': typeof mainUnauthorizedRoute
  '/': typeof externalIndexRoute
  '/auth/v2': typeof mainAuthV2RouteRouteWithChildren
  '/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/dashboard/deposits': typeof mainDashboardDepositsRouteRoute
  '/dashboard/deposits/': typeof mainDashboardDepositsIndexRoute
  '/dashboard/deposits/depoist-details': typeof mainDashboardDepositsDepoistDetailsRouteRoute
  '/dashboard/deposits/depoist-details/': typeof mainDashboardDepositsDepoistDetailsIndexRoute
  '/dashboard/deposits/depoist-details/voucher': typeof mainDashboardDepositsDepoistDetailsVoucherRouteRoute
  '/dashboard/withdrawls': typeof mainDashboardWithdrawlsRouteRoute
  '/dashboard/withdrawls/analytics': typeof mainDashboardWithdrawlsAnalyticsRouteRoute
  '/dashboard/players': typeof mainDashboardPlayersRouteRoute
  '/dashboard/players/$playerId': typeof mainDashboardPlayersProfileRouteRoute
  '/dashboard/distributors': typeof mainDashboardDistributorsRouteRouteWithChildren
  '/dashboard/distributors/account': typeof mainDashboardDistributorsAccountRouteRoute
  '/portal': typeof mainPortalRouteRouteWithChildren
  '/portal/$method': typeof mainPortalMethodRouteRoute
  '/portal/tracking-depoist': typeof mainPortalTrackingDepoistRouteRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/auth/v1/register': typeof mainAuthV1RegisterRouteRoute
  '/auth/v2/login': typeof mainAuthV2LoginRouteRoute
  '/auth/v2/register': typeof mainAuthV2RegisterRouteRoute
  '/dashboard/deposits/': typeof mainDashboardDepositsIndexRoute
  '/dashboard/deposits/depoist-details': typeof mainDashboardDepositsDepoistDetailsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/chat': typeof mainChatRouteRoute
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(main)/mail': typeof mainMailRouteRoute
  '/(main)/unauthorized': typeof mainUnauthorizedRoute
  '/(external)/': typeof externalIndexRoute
  '/(main)/auth/v2': typeof mainAuthV2RouteRouteWithChildren
  '/(main)/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/(main)/dashboard/settings': typeof mainDashboardSettingsRouteRouteWithChildren
  '/(main)/dashboard/settings/general': typeof mainDashboardSettingsGeneralRouteRoute
  '/(main)/dashboard/settings/languages': typeof mainDashboardSettingsLanguagesRouteRoute
  '/(main)/dashboard/settings/security': typeof mainDashboardSettingsSecurityRouteRoute
  '/(main)/dashboard/settings/notifications': typeof mainDashboardSettingsNotificationsRouteRoute
  '/(main)/dashboard/settings/audit-log': typeof mainDashboardSettingsAuditLogRouteRoute
  '/(main)/dashboard/settings/billing': typeof mainDashboardSettingsBillingRouteRoute
  '/(main)/dashboard/settings/features': typeof mainDashboardSettingsFeaturesRouteRoute
  '/(main)/dashboard/settings/custom-domain': typeof mainDashboardSettingsCustomDomainRouteRoute
  '/(main)/dashboard/settings/team-access': typeof mainDashboardSettingsTeamAccessRouteRoute
  '/(main)/dashboard/integrations': typeof mainDashboardIntegrationsRouteRoute
  '/(main)/dashboard/portal': typeof mainDashboardPortalRouteRoute
  '/(main)/dashboard/deposits': typeof mainDashboardDepositsRouteRoute
  '/(main)/dashboard/deposits/': typeof mainDashboardDepositsIndexRoute
  '/(main)/dashboard/deposits/depoist-details': typeof mainDashboardDepositsDepoistDetailsRouteRoute
  '/(main)/dashboard/deposits/depoist-details/': typeof mainDashboardDepositsDepoistDetailsIndexRoute
  '/(main)/dashboard/deposits/depoist-details/voucher': typeof mainDashboardDepositsDepoistDetailsVoucherRouteRoute
  '/(main)/dashboard/withdrawls': typeof mainDashboardWithdrawlsRouteRoute
  '/(main)/dashboard/withdrawls_/analytics': typeof mainDashboardWithdrawlsAnalyticsRouteRoute
  '/(main)/dashboard/players': typeof mainDashboardPlayersRouteRoute
  '/(main)/dashboard/players/$playerId': typeof mainDashboardPlayersProfileRouteRoute
  '/(main)/dashboard/distributors': typeof mainDashboardDistributorsRouteRoute
  '/(main)/dashboard/distributors_/account': typeof mainDashboardDistributorsAccountRouteRoute
  '/(main)/dashboard/accounts': typeof mainDashboardAccountsRouteRoute
  '/(main)/portal': typeof mainPortalRouteRouteWithChildren
  '/(main)/portal/$method': typeof mainPortalMethodRouteRoute
  '/(main)/portal/tracking-depoist': typeof mainPortalTrackingDepoistRouteRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/(main)/auth/v1/register': typeof mainAuthV1RegisterRouteRoute
  '/(main)/auth/v2/login': typeof mainAuthV2LoginRouteRoute
  '/(main)/auth/v2/register': typeof mainAuthV2RegisterRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/dashboard'
    | '/mail'
    | '/unauthorized'
    | '/'
    | '/auth/v2'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/dashboard/settings/general'
    | '/dashboard/settings/languages'
    | '/dashboard/settings/security'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/audit-log'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/features'
    | '/dashboard/settings/custom-domain'
    | '/dashboard/settings/team-access'
    | '/dashboard/settings/custom-domain'
    | '/dashboard/settings/team-access'
    | '/dashboard/integrations'
    | '/dashboard/portal'
    | '/dashboard/settings'
    | '/dashboard/settings/general'
    | '/dashboard/settings/languages'
    | '/dashboard/settings/security'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/audit-log'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/features'
    | '/dashboard/integrations'
    | '/dashboard/portal'
    | '/dashboard/deposits'
    | '/dashboard/deposits/'
    | '/dashboard/deposits/depoist-details'
        | '/dashboard/withdrawls'
    | '/dashboard/withdrawls/analytics'
    | '/dashboard/deposits'
    | '/dashboard/withdrawls'
    | '/dashboard/players'
    | '/dashboard/players/$playerId'
    | '/dashboard/players/$playerId'
    | '/dashboard/distributors'
    | '/dashboard/distributors/account'
    | '/dashboard/distributors/account'
    | '/dashboard/accounts'
    | '/dashboard/$'
    | '/portal'
    | '/portal/$method'
    | '/portal/tracking-depoist'
    | '/dashboard/'
    | '/auth/v1/login'
    | '/auth/v1/register'
    | '/auth/v2/login'
    | '/auth/v2/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/mail'
    | '/unauthorized'
    | '/'
    | '/auth/v2'
    | '/dashboard/analytics'
    | '/dashboard/withdrawls/analytics'
    | '/dashboard/distributors'
    | '/dashboard/'
    | '/portal'
    | '/portal/$method'
    | '/portal/tracking-depoist'
    | '/dashboard'
    | '/auth/v1/login'
    | '/auth/v1/register'
    | '/auth/v2/login'
    | '/auth/v2/register'
  id:
    | '__root__'
    | '/(main)/chat'
    | '/(main)/dashboard'
    | '/(main)/mail'
    | '/(main)/unauthorized'
    | '/(external)/'
    | '/(main)/auth/v2'
    | '/(main)/dashboard/analytics'
    | '/(main)/dashboard/settings'
    | '/(main)/dashboard/settings/general'
    | '/(main)/dashboard/settings/languages'
    | '/(main)/dashboard/settings/security'
    | '/(main)/dashboard/settings/notifications'
    | '/(main)/dashboard/settings/audit-log'
    | '/(main)/dashboard/settings/billing'
    | '/(main)/dashboard/settings/features'
    | '/(main)/dashboard/settings/custom-domain'
    | '/(main)/dashboard/settings/team-access'
    | '/(main)/dashboard/integrations'
    | '/(main)/dashboard/portal'
    | '/(main)/dashboard/deposits'
    | '/(main)/dashboard/withdrawls'
    | '/(main)/dashboard/withdrawls_/analytics'
    | '/(main)/dashboard/players'
    | '/(main)/dashboard/players/$playerId'
    | '/(main)/dashboard/distributors'
    | '/(main)/portal'
    | '/(main)/portal/$method'
    | '/(main)/portal/tracking-depoist'
    | '/(main)/dashboard/'
    | '/(main)/auth/v1/login'
    | '/(main)/auth/v1/register'
    | '/(main)/auth/v2/login'
    | '/(main)/auth/v2/register'
    | '/(main)/dashboard/(legacy)/analytics-v1'
    | '/(main)/dashboard/(legacy)/crm-v1'
    | '/(main)/dashboard/(legacy)/default-v1'
    | '/(main)/dashboard/(legacy)/finance-v1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainChatRouteRoute: typeof mainChatRouteRoute
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
  mainMailRouteRoute: typeof mainMailRouteRoute
  mainUnauthorizedRoute: typeof mainUnauthorizedRoute
  externalIndexRoute: typeof externalIndexRoute
  mainAuthV2RouteRoute: typeof mainAuthV2RouteRouteWithChildren
  mainAuthV1LoginRouteRoute: typeof mainAuthV1LoginRouteRoute
  mainAuthV1RegisterRouteRoute: typeof mainAuthV1RegisterRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(external)/': {
      id: '/(external)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof externalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/chat': {
      id: '/(main)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof mainChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/portal': {
      id: '/(main)/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof mainPortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/portal/$method': {
      id: '/(main)/portal/$method'
      path: '/$method'
      fullPath: '/portal/$method'
      preLoaderRoute: typeof mainPortalMethodRouteRouteImport
      parentRoute: typeof mainPortalRouteRoute
    }
    '/(main)/portal/tracking-depoist': {
      id: '/(main)/portal/tracking-depoist'
      path: '/tracking-depoist'
      fullPath: '/portal/tracking-depoist'
      preLoaderRoute: typeof mainPortalTrackingDepoistRouteRouteImport
      parentRoute: typeof mainPortalRouteRoute
    }
    '/(main)/mail': {
      id: '/(main)/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof mainMailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/unauthorized': {
      id: '/(main)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof mainUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/v2': {
      id: '/(main)/auth/v2'
      path: '/auth/v2'
      fullPath: '/auth/v2'
      preLoaderRoute: typeof mainAuthV2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/$': {
      id: '/(main)/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof mainDashboardSplatRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/academy'
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/analytics': {
      id: '/(main)/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof mainDashboardAnalyticsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/calendar'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/chat'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/coming-soon'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/crm'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/default'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/ecommerce'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/finance'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/transactions'
    }
      path: '/treasury'
    }
      path: '/settlements'
    }
      path: '/reports'
    }
      path: '/financial-performance'
    }
      path: '/provider-performance'
    }
      path: '/distributor-performance'
    }
      path: '/fees-compensation'
    }
      path: '/settlement-report'
    }
      path: '/reconciliation-report'
    }
    '/(main)/dashboard/settings': {
      id: '/(main)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof mainDashboardSettingsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/settings/general': {
      id: '/(main)/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof mainDashboardSettingsGeneralRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/languages': {
      id: '/(main)/dashboard/settings/languages'
      path: '/languages'
      fullPath: '/dashboard/settings/languages'
      preLoaderRoute: typeof mainDashboardSettingsLanguagesRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/security': {
      id: '/(main)/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof mainDashboardSettingsSecurityRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/notifications': {
      id: '/(main)/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof mainDashboardSettingsNotificationsRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/audit-log': {
      id: '/(main)/dashboard/settings/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/settings/audit-log'
      preLoaderRoute: typeof mainDashboardSettingsAuditLogRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/billing': {
      id: '/(main)/dashboard/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof mainDashboardSettingsBillingRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/features': {
      id: '/(main)/dashboard/settings/features'
      path: '/features'
      fullPath: '/dashboard/settings/features'
      preLoaderRoute: typeof mainDashboardSettingsFeaturesRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/custom-domain': {
      id: '/(main)/dashboard/settings/custom-domain'
      path: '/custom-domain'
      fullPath: '/dashboard/settings/custom-domain'
      preLoaderRoute: typeof mainDashboardSettingsCustomDomainRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/settings/team-access': {
      id: '/(main)/dashboard/settings/team-access'
      path: '/team-access'
      fullPath: '/dashboard/settings/team-access'
      preLoaderRoute: typeof mainDashboardSettingsTeamAccessRouteRouteImport
      parentRoute: typeof mainDashboardSettingsRouteRoute
    }
    '/(main)/dashboard/integrations': {
      id: '/(main)/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof mainDashboardIntegrationsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/portal': {
      id: '/(main)/dashboard/portal'
      path: '/portal'
      fullPath: '/dashboard/portal'
      preLoaderRoute: typeof mainDashboardPortalRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/profile'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/file-manager'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/patient-monitoring'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/infrastructure'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/invoice'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/kanban'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/logistics'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/mail'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/productivity'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/roles'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/tasks'
      parentRoute: typeof mainDashboardRouteRoute
    }
      path: '/users'
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/deposits': {
      id: '/(main)/dashboard/deposits'
      path: '/deposits'
      fullPath: '/dashboard/deposits'
      preLoaderRoute: typeof mainDashboardDepositsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/deposits/': {
      id: '/(main)/dashboard/deposits/'
      path: '/'
      fullPath: '/dashboard/deposits/'
      preLoaderRoute: typeof mainDashboardDepositsIndexRouteImport
      parentRoute: typeof mainDashboardDepositsRouteRoute
    }
    '/(main)/dashboard/deposits/depoist-details': {
      id: '/(main)/dashboard/deposits/depoist-details'
      path: '/depoist-details'
      fullPath: '/dashboard/deposits/depoist-details'
      preLoaderRoute: typeof mainDashboardDepositsDepoistDetailsRouteRouteImport
      parentRoute: typeof mainDashboardDepositsRouteRoute
    }
    '/(main)/dashboard/deposits/depoist-details/': {
      id: '/(main)/dashboard/deposits/depoist-details/'
      path: '/'
      fullPath: '/dashboard/deposits/depoist-details/'
      preLoaderRoute: typeof mainDashboardDepositsDepoistDetailsIndexRouteImport
      parentRoute: typeof mainDashboardDepositsDepoistDetailsRouteRoute
    }
    '/(main)/dashboard/deposits/depoist-details/voucher': {
      id: '/(main)/dashboard/deposits/depoist-details/voucher'
      path: '/voucher'
      fullPath: '/dashboard/deposits/depoist-details/voucher'
      preLoaderRoute: typeof mainDashboardDepositsDepoistDetailsVoucherRouteImport
      parentRoute: typeof mainDashboardDepositsDepoistDetailsRouteRoute
    }

    '/(main)/dashboard/withdrawls': {
      id: '/(main)/dashboard/withdrawls'
      path: '/withdrawls'
      fullPath: '/dashboard/withdrawls'
      preLoaderRoute: typeof mainDashboardWithdrawlsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/withdrawls_/analytics': {
      id: '/(main)/dashboard/withdrawls_/analytics'
      path: '/analytics'
      fullPath: '/dashboard/withdrawls/analytics'
      preLoaderRoute: typeof mainDashboardWithdrawlsAnalyticsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/players': {
      id: '/(main)/dashboard/players'
      path: '/players'
      fullPath: '/dashboard/players'
      preLoaderRoute: typeof mainDashboardPlayersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/players/$playerId': {
      id: '/(main)/dashboard/players/$playerId'
      path: '/$playerId'
      fullPath: '/dashboard/players/$playerId'
      preLoaderRoute: typeof mainDashboardPlayersProfileRouteRouteImport
      parentRoute: typeof mainDashboardPlayersRouteRoute
    }
    '/(main)/dashboard/distributors': {
      id: '/(main)/dashboard/distributors'
      path: '/distributors'
      fullPath: '/dashboard/distributors'
      preLoaderRoute: typeof mainDashboardDistributorsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/distributors_/account': {
      id: '/(main)/dashboard/distributors_/account'
      path: '/distributors/account'
      fullPath: '/dashboard/distributors/account'
      preLoaderRoute: typeof mainDashboardDistributorsAccountRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/accounts': {
      id: '/(main)/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof mainDashboardAccountsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/auth/v1/login': {
      id: '/(main)/auth/v1/login'
      path: '/auth/v1/login'
      fullPath: '/auth/v1/login'
      preLoaderRoute: typeof mainAuthV1LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/v1/register': {
      id: '/(main)/auth/v1/register'
      path: '/auth/v1/register'
      fullPath: '/auth/v1/register'
      preLoaderRoute: typeof mainAuthV1RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/v2/login': {
      id: '/(main)/auth/v2/login'
      path: '/login'
      fullPath: '/auth/v2/login'
      preLoaderRoute: typeof mainAuthV2LoginRouteRouteImport
      parentRoute: typeof mainAuthV2RouteRoute
    }
    '/(main)/auth/v2/register': {
      id: '/(main)/auth/v2/register'
      path: '/register'
      fullPath: '/auth/v2/register'
      preLoaderRoute: typeof mainAuthV2RegisterRouteRouteImport
      parentRoute: typeof mainAuthV2RouteRoute
    }
    '/(main)/dashboard/(legacy)/analytics-v1': {
      id: '/(main)/dashboard/(legacy)/analytics-v1'
      path: '/analytics-v1'
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/(legacy)/crm-v1': {
      id: '/(main)/dashboard/(legacy)/crm-v1'
      path: '/crm-v1'
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/(legacy)/default-v1': {
      id: '/(main)/dashboard/(legacy)/default-v1'
      path: '/default-v1'
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/(legacy)/finance-v1': {
      id: '/(main)/dashboard/(legacy)/finance-v1'
      path: '/finance-v1'
      parentRoute: typeof mainDashboardRouteRoute
    }
  }
}

interface mainDashboardDepositsDepoistDetailsRouteRouteChildren {
  mainDashboardDepositsDepoistDetailsIndexRoute: typeof mainDashboardDepositsDepoistDetailsIndexRoute
  mainDashboardDepositsDepoistDetailsVoucherRouteRoute: typeof mainDashboardDepositsDepoistDetailsVoucherRouteRoute
}

const mainDashboardDepositsDepoistDetailsRouteRouteChildren: mainDashboardDepositsDepoistDetailsRouteRouteChildren = {
  mainDashboardDepositsDepoistDetailsIndexRoute: mainDashboardDepositsDepoistDetailsIndexRoute,
  mainDashboardDepositsDepoistDetailsVoucherRouteRoute: mainDashboardDepositsDepoistDetailsVoucherRouteRoute,
}

const mainDashboardDepositsDepoistDetailsRouteRouteWithChildren =
  mainDashboardDepositsDepoistDetailsRouteRoute._addFileChildren(mainDashboardDepositsDepoistDetailsRouteRouteChildren)

interface mainDashboardDepositsRouteRouteChildren {
  mainDashboardDepositsIndexRoute: typeof mainDashboardDepositsIndexRoute
  mainDashboardDepositsDepoistDetailsRouteRoute: typeof mainDashboardDepositsDepoistDetailsRouteRouteWithChildren
}

const mainDashboardDepositsRouteRouteChildren: mainDashboardDepositsRouteRouteChildren = {
  mainDashboardDepositsIndexRoute: mainDashboardDepositsIndexRoute,
  mainDashboardDepositsDepoistDetailsRouteRoute: mainDashboardDepositsDepoistDetailsRouteRouteWithChildren,
}

const mainDashboardDepositsRouteRouteWithChildren =
  mainDashboardDepositsRouteRoute._addFileChildren(mainDashboardDepositsRouteRouteChildren)

}

}

interface mainDashboardSettingsRouteRouteChildren {
  mainDashboardSettingsGeneralRouteRoute: typeof mainDashboardSettingsGeneralRouteRoute
  mainDashboardSettingsLanguagesRouteRoute: typeof mainDashboardSettingsLanguagesRouteRoute
  mainDashboardSettingsSecurityRouteRoute: typeof mainDashboardSettingsSecurityRouteRoute
  mainDashboardSettingsNotificationsRouteRoute: typeof mainDashboardSettingsNotificationsRouteRoute
  mainDashboardSettingsAuditLogRouteRoute: typeof mainDashboardSettingsAuditLogRouteRoute
  mainDashboardSettingsBillingRouteRoute: typeof mainDashboardSettingsBillingRouteRoute
  mainDashboardSettingsFeaturesRouteRoute: typeof mainDashboardSettingsFeaturesRouteRoute
  mainDashboardSettingsCustomDomainRouteRoute: typeof mainDashboardSettingsCustomDomainRouteRoute
  mainDashboardSettingsTeamAccessRouteRoute: typeof mainDashboardSettingsTeamAccessRouteRoute
}

const mainDashboardSettingsRouteRouteChildren: mainDashboardSettingsRouteRouteChildren = {
  mainDashboardSettingsGeneralRouteRoute: mainDashboardSettingsGeneralRouteRoute,
  mainDashboardSettingsLanguagesRouteRoute: mainDashboardSettingsLanguagesRouteRoute,
  mainDashboardSettingsSecurityRouteRoute: mainDashboardSettingsSecurityRouteRoute,
  mainDashboardSettingsNotificationsRouteRoute: mainDashboardSettingsNotificationsRouteRoute,
  mainDashboardSettingsAuditLogRouteRoute: mainDashboardSettingsAuditLogRouteRoute,
  mainDashboardSettingsBillingRouteRoute: mainDashboardSettingsBillingRouteRoute,
  mainDashboardSettingsFeaturesRouteRoute: mainDashboardSettingsFeaturesRouteRoute,
  mainDashboardSettingsCustomDomainRouteRoute: mainDashboardSettingsCustomDomainRouteRoute,
  mainDashboardSettingsTeamAccessRouteRoute: mainDashboardSettingsTeamAccessRouteRoute,
}

const mainDashboardSettingsRouteRouteWithChildren =
  mainDashboardSettingsRouteRoute._addFileChildren(mainDashboardSettingsRouteRouteChildren)

interface mainDashboardPlayersRouteRouteChildren {
  mainDashboardPlayersProfileRouteRoute: typeof mainDashboardPlayersProfileRouteRoute
}

const mainDashboardPlayersRouteRouteChildren: mainDashboardPlayersRouteRouteChildren = {
  mainDashboardPlayersProfileRouteRoute: mainDashboardPlayersProfileRouteRoute,
}

const mainDashboardPlayersRouteRouteWithChildren =
  mainDashboardPlayersRouteRoute._addFileChildren(mainDashboardPlayersRouteRouteChildren)


interface mainPortalRouteRouteChildren {
  mainPortalMethodRouteRoute: typeof mainPortalMethodRouteRoute
  mainPortalTrackingDepoistRouteRoute: typeof mainPortalTrackingDepoistRouteRoute
}

const mainPortalRouteRouteChildren: mainPortalRouteRouteChildren = {
  mainPortalMethodRouteRoute: mainPortalMethodRouteRoute,
  mainPortalTrackingDepoistRouteRoute: mainPortalTrackingDepoistRouteRoute,
}

const mainPortalRouteRouteWithChildren =
  mainPortalRouteRoute._addFileChildren(mainPortalRouteRouteChildren)

interface mainDashboardRouteRouteChildren {
  mainDashboardAnalyticsRouteRoute: typeof mainDashboardAnalyticsRouteRoute
  mainDashboardDepositsRouteRoute: typeof mainDashboardDepositsRouteRoute
  mainDashboardWithdrawlsRouteRoute: typeof mainDashboardWithdrawlsRouteRoute
  mainDashboardPlayersRouteRoute: typeof mainDashboardPlayersRouteRoute
  mainDashboardSplatRoute: typeof mainDashboardSplatRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardAnalyticsRouteRoute: mainDashboardAnalyticsRouteRoute,
  mainDashboardDepositsRouteRoute: mainDashboardDepositsRouteRouteWithChildren,
  mainDashboardWithdrawlsRouteRoute: mainDashboardWithdrawlsRouteRoute,
  mainDashboardPlayersRouteRoute: mainDashboardPlayersRouteRoute,
  mainDashboardSplatRoute: mainDashboardSplatRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

interface mainAuthV2RouteRouteChildren {
  mainAuthV2LoginRouteRoute: typeof mainAuthV2LoginRouteRoute
  mainAuthV2RegisterRouteRoute: typeof mainAuthV2RegisterRouteRoute
}

const mainAuthV2RouteRouteChildren: mainAuthV2RouteRouteChildren = {
  mainAuthV2LoginRouteRoute: mainAuthV2LoginRouteRoute,
  mainAuthV2RegisterRouteRoute: mainAuthV2RegisterRouteRoute,
}

const mainAuthV2RouteRouteWithChildren = mainAuthV2RouteRoute._addFileChildren(
  mainAuthV2RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainChatRouteRoute: mainChatRouteRoute,
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
  mainPortalRouteRoute: mainPortalRouteRouteWithChildren,
  mainMailRouteRoute: mainMailRouteRoute,
  mainUnauthorizedRoute: mainUnauthorizedRoute,
  externalIndexRoute: externalIndexRoute,
  mainAuthV2RouteRoute: mainAuthV2RouteRouteWithChildren,
  mainAuthV1LoginRouteRoute: mainAuthV1LoginRouteRoute,
  mainAuthV1RegisterRouteRoute: mainAuthV1RegisterRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}